--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Debian 16.4-1.pgdg120+1)
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: user_role; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.user_role AS ENUM (
    'Admin',
    'Financial',
    'TeamLeadMediabuyer',
    'Mediabuyer',
    'TeamLeadProcessor',
    'Processor'
);


ALTER TYPE public.user_role OWNER TO postgres;

--
-- Name: user_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.user_status AS ENUM (
    'Active',
    'Inactive',
    'Deleted'
);


ALTER TYPE public.user_status OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audience; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.audience (
    id integer NOT NULL,
    pixel_id character varying(255),
    user_id character varying(255),
    username character varying(255),
    chat_id character varying(255),
    status character varying(255),
    channel_name character varying(255),
    invite_code character varying(255),
    placement character varying(255),
    site_source_name character varying(255),
    ad_id character varying(255),
    ad_name character varying(255),
    adset_id character varying(255),
    adset_name character varying(255),
    campaign_id character varying(255),
    campaign_name character varying(255),
    fbclid character varying(255),
    client_user_agent character varying(255),
    client_ip_address character varying(255),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.audience OWNER TO postgres;

--
-- Name: audience_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.audience ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audience_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO postgres;

--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO postgres;

--
-- Name: pixel; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pixel (
    id integer NOT NULL,
    owner character varying(255),
    pixel_title character varying(255),
    pixel_id character varying(255),
    pixel_api character varying(255),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.pixel OWNER TO postgres;

--
-- Name: pixel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pixel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pixel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: telegram_channel; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.telegram_channel (
    id integer NOT NULL,
    channel_id character varying(255),
    channel_name character varying(255),
    channel_bot character varying(255),
    fb_pixel character varying(255),
    telegram_account character varying(255),
    "hashId" character varying(255),
    btn_link character varying(255),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.telegram_channel OWNER TO postgres;

--
-- Name: telegram_channel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.telegram_channel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.telegram_channel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    username character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    "authKey" character varying(255),
    "accessToken" character varying(255),
    role public.user_role DEFAULT 'Processor'::public.user_role NOT NULL,
    status public.user_status DEFAULT 'Active'::public.user_status NOT NULL,
    telegram_accounts character varying(255) DEFAULT ''::character varying,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public."user" OWNER TO postgres;

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: audience; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.audience (id, pixel_id, user_id, username, chat_id, status, channel_name, invite_code, placement, site_source_name, ad_id, ad_name, adset_id, adset_name, campaign_id, campaign_name, fbclid, client_user_agent, client_ip_address, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
1	dkarp	changelog/001_create_users_table.yaml	2024-08-26 21:18:16.493747	1	EXECUTED	9:4af00479005a6d9a155e3d583cdadad9	sql		\N	4.29.1	\N	\N	4707096443
2	dkarp	changelog/001_create_users_table.yaml	2024-08-26 21:18:16.503093	2	EXECUTED	9:18c5077d033375ba576730f8c04e7a70	sql		\N	4.29.1	\N	\N	4707096443
3	dkarp	changelog/001_create_users_table.yaml	2024-08-26 21:18:16.533286	3	EXECUTED	9:e2782c273ae490adde3806b5a46e290e	createTable tableName=user		\N	4.29.1	\N	\N	4707096443
4	dkarp	changelog/001_create_users_table.yaml	2024-08-26 21:18:16.548109	4	EXECUTED	9:ec638b9cf64c0c3466b24f94caca9b16	addUniqueConstraint constraintName=unique_username, tableName=user		\N	4.29.1	\N	\N	4707096443
5	dkarp	changelog/001_create_users_table.yaml	2024-08-26 21:18:16.560495	5	EXECUTED	9:3cd37fca422187005c8555ec1f397106	sql		\N	4.29.1	\N	\N	4707096443
1	dkarp	changelog/002_create_audience_table.yaml	2024-08-26 21:18:16.586182	6	EXECUTED	9:cccbf626749328b88083d5c79dd41619	createTable tableName=audience		\N	4.29.1	\N	\N	4707096443
1	dkarp	changelog/003_create_pixel_table.yaml	2024-08-26 21:18:16.614207	7	EXECUTED	9:340973f3ddab2b78215445d9d5de4ef7	createTable tableName=pixel		\N	4.29.1	\N	\N	4707096443
1	dkarp	changelog/004_create_telegram_channel_table.yaml	2024-08-26 21:18:16.635165	8	EXECUTED	9:3ec2a6d0bea39d50c264a9a6394b91d6	createTable tableName=telegram_channel		\N	4.29.1	\N	\N	4707096443
\.


--
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- Data for Name: pixel; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pixel (id, owner, pixel_title, pixel_id, pixel_api, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: telegram_channel; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.telegram_channel (id, channel_id, channel_name, channel_bot, fb_pixel, telegram_account, "hashId", btn_link, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."user" (id, username, password_hash, "authKey", "accessToken", role, status, telegram_accounts, created_at, updated_at) FROM stdin;
1	dev	$2a$12$vPXesKG1eZDKhWl6yMC27.K6LMGCUSOOKsGJIBxyGG1v0zLOTKYw6	test100key	100-token	Admin	Active		2024-08-26 21:18:16.551791	2024-08-26 21:18:16.551791
2	test	$2y$13$gxLlDlFrYV1gjzt/TfAP4.Jx0i7u47JIyPBJr8cNuX0gg9iGuJ3o2	_-IUHyS_MB98ISVNQwzNArErwNKEU3Vj	cbBghvwnmi_5Gyo-f_hgBFHJLLNVmpZr	Admin	Active	[]	2024-08-26 21:18:35	2024-08-26 21:18:35
\.


--
-- Name: audience_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.audience_id_seq', 1, false);


--
-- Name: pixel_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pixel_id_seq', 1, false);


--
-- Name: telegram_channel_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.telegram_channel_id_seq', 1, false);


--
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_id_seq', 2, true);


--
-- Name: audience audience_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audience
    ADD CONSTRAINT audience_pkey PRIMARY KEY (id);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: pixel pixel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pixel
    ADD CONSTRAINT pixel_pkey PRIMARY KEY (id);


--
-- Name: telegram_channel telegram_channel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.telegram_channel
    ADD CONSTRAINT telegram_channel_pkey PRIMARY KEY (id);


--
-- Name: user unique_username; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT unique_username UNIQUE (username);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

