services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: no
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html/arbitrage-shark/
      - ./config/server/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/server/nginx.conf:/etc/nginx/nginx.conf
      - ./config/server/ssl:/etc/nginx/ssl
    depends_on:
      - crm
    networks:
      - web_network

  liquibase:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: liquibase
    restart: no
    networks:
      - web_network

  crm:
    build:
      context: ./crm
      dockerfile: Dockerfile
    container_name: crm
    restart: on-failure
    volumes:
      - ./crm:/var/www/html/arbitrage-shark/crm
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
