services:
  crm:
    build:
      context: ./crm
      dockerfile: Dockerfile
    container_name: crm
    volumes:
      - ./crm:/var/www/html/arbitrage-shark/crm
    ports:
      - "9001:9000"
    networks:
      - yii2_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/arbitrage-shark/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - crm
    networks:
      - yii2_network

  pgsql:
    image: postgres:16
    container_name: pgsql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: defaultdb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - yii2_network

networks:
  yii2_network:

volumes:
  pg_data: