services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: no
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html/arbitrage-shark/
      - ./config/server/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/server/nginx.conf:/etc/nginx/nginx.conf
      - ./config/server/ssl:/etc/nginx/ssl
    depends_on:
      - crm
    networks:
      - web_network

  liquibase:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: liquibase
    restart: no
    environment:
      DB_URL: "jdbc:postgresql://vultr-prod-47ece5d5-eb9c-4855-94c5-8804581daa12-vultr-prod-92d7.vultrdb.com:16751/audience-postgres"
      POSTGRES_USER: "vultradmin"
      POSTGRES_PASSWORD: "AVNS_nLThkCM8QhWbexMvWAk"
    networks:
      - web_network

  crm:
    build:
      context: ./crm
      dockerfile: Dockerfile
    container_name: crm
    restart: on-failure
    environment:
      DB_DSN: "pgsql:host=vultr-prod-47ece5d5-eb9c-4855-94c5-8804581daa12-vultr-prod-92d7.vultrdb.com;port=16751;dbname=audience-postgres"
      DB_USER: "vultradmin"
      DB_PASS: "AVNS_nLThkCM8QhWbexMvWAk"
    volumes:
      - ./crm:/var/www/html/arbitrage-shark/crm
    networks:
      - web_network

  bot_service:
    build:
      context: ./bot_service
      dockerfile: Dockerfile
    container_name: bot_service
    restart: on-failure
    environment:
      DB_DSN: "pgsql:host=vultr-prod-47ece5d5-eb9c-4855-94c5-8804581daa12-vultr-prod-92d7.vultrdb.com;port=16751;dbname=audience-postgres"
      DB_USER: "vultradmin"
      DB_PASS: "AVNS_nLThkCM8QhWbexMvWAk"
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
