services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/arbitrage-shark/
      - ./config/server/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/server/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - crm
    networks:
      - yii2_network

  liquibase:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: liquibase
    depends_on:
      - postgresdb
    networks:
      - yii2_network

  postgresdb:
    image: postgres:latest
    container_name: "postgresdb"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - yii2_network

  backup:
    build: ./backup
    container_name: db_backup
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - ./backups:/backups
    depends_on:
      - postgresdb
    networks:
      - yii2_network

  crm:
    build:
      context: ./crm
      dockerfile: Dockerfile
    container_name: crm
    restart: always
    volumes:
      - ./crm:/var/www/html/arbitrage-shark/crm
    networks:
      - yii2_network

volumes:
  pg_data:
  backups:

networks:
  yii2_network: