services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/arbitrage-shark/
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - crm
      - redirect-service
    networks:
      - yii2_network
    restart: always

  crm:
    build:
      context: ./crm
      dockerfile: Dockerfile
    container_name: crm
    volumes:
      - ./crm:/var/www/html/arbitrage-shark/crm
    networks:
      - yii2_network

  redirect-service:
    build:
      context: redirect-service
      dockerfile: Dockerfile
    container_name: redirect-service
    volumes:
      - ./redirect-service:/var/www/html/arbitrage-shark/redirect-service
    networks:
      - yii2_network

  pgsql:
    image: postgres:16
    container_name: pgsql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: defaultdb
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - yii2_network
    restart: always

networks:
  yii2_network:
#
#volumes:
#  pg_data: