services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/arbitrage-shark/
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - crm
    networks:
      - yii2_network
    restart: always

  crm:
    build:
      context: ./crm
      dockerfile: Dockerfile
    container_name: crm
    restart: always
    volumes:
      - ./crm:/var/www/html/arbitrage-shark/crm
    networks:
      - yii2_network
    depends_on:
      - db

  liquibase:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: liquibase
    depends_on:
      - db
    networks:
      - yii2_network

  db:
    image: postgres:alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
        - yii2_network
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
    db_data:

networks:
  yii2_network:
    driver: bridge