services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: no
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html/arbitrage-shark/
      - ./config/server/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/server/nginx.conf:/etc/nginx/nginx.conf
      - ./config/server/ssl:/etc/nginx/ssl
    depends_on:
      - crm
    networks:
      - web_network

  liquibase:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: liquibase
    restart: no
    networks:
      - web_network

  crm:
    build:
      context: ./crm
      dockerfile: Dockerfile
    container_name: crm
    restart: on-failure
    volumes:
      - ./crm:/var/www/html/arbitrage-shark/crm
    networks:
      - web_network

  postgresdb:
    image: postgres:latest
    container_name: "postgresdb"
    restart: no
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - web_network

  bot-service:
    build:
      context: ./bot-service
      dockerfile: Dockerfile
    container_name: bot-service
    restart: on-failure
    volumes:
      - ./bot-service:/var/www/html/arbitrage-shark/bot-service
    networks:
      - web_network

networks:
  web_network:
    driver: bridge