services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/arbitrage-shark/
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - crm
    networks:
      - yii2_network
    restart: always

  crm:
    build:
      context: ./crm
      dockerfile: Dockerfile
    container_name: crm
    restart: always
    volumes:
      - ./crm:/var/www/html/arbitrage-shark/crm
    networks:
      - yii2_network

  bot-service:
    build:
      context: ./bot-service
      dockerfile: Dockerfile
    container_name: bot-service
    restart: always
    volumes:
      - ./bot-service:/var/www/html/arbitrage-shark/bot-service
    networks:
      - yii2_network

networks:
  yii2_network: