version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-cards-server
    ports:
      - '5002:5002'
    environment:
      - NODE_ENV=production
      - API_ID=your_api_id
      - API_HASH=your_api_hash
      - SERVER_PORT=5002
